### ISSUE TITLE
Thanks for exercizes. Will you add more?

### ISSUE THREAD

**Issue by gcloeval** [glenacota/elastic-training-repo#2]
Thanks a lot for your exercizes, very useful to me while i am preparing for the exam.

Do you have plans to add more examples to cover the other objectives?

Either way thanks a lot.

**Comment by glenacota** [comment]
Thanks, my pleasure!
Yes, within one month I'll upload more exercises to cover the Search and Aggregations objectives. As for your preparation, please take into account that soon the exam will be upgraded to version 7.x of Elasticsearch. Therefore, parts of the current exercises might get obsoleted. I'll create an issue for updating them :)
