### ISSUE TITLE
Question on exercise in O3a_text_highlight_pagination_sort

### ISSUE THREAD

**Issue by WaaZaa666** [glenacota/elastic-training-repo#5]
I was working through these, but am wondering what the answer would be for the 2nd part of this question: 

`# Run the next queries on the `kibana_sample_data_ecommerce` index
- search for documents with the `day_of_week` field containing the string "Monday"
- As above, but sort the results by the `products.base_price` field in descending order, picking the lowest value of the array`

I was working towards a nested query, but I then saw in 7.2 the sample ecommerce does not contain nested objects, so I was kinda clueless how to get this..

**Comment by glenacota** [comment]
Hey, wow, sorry for the super late reply. 
Hope you found your answer in the docs, in the meantime: https://www.elastic.co/guide/en/elasticsearch/reference/7.2/search-request-sort.html#_sort_mode_option
